### ISSUE TITLE
Exception with 0.2 and IntelliJ 2017.3 ultimate

### ISSUE THREAD

**Issue by sebvige** [rhdunn/marklogic-intellij-plugin#21]
Hello, 

We get the following exception starting up IntelliJ with plugin v0.2 installed. 
The plugin partially works in 2017.2.6 but not at all in 2017.3 - generating the exception below.

The xqy part does work with Intellij v 2017.2.6 but not in 2017.3.

sjs modules are not working at all in both version of IJ

The intelliJ interface as change a lot on the plugin management UI from 2017.2.6 and 2017.3 and thare might be some side effect on the plugin behaviour.

We have been able to set MarkLogic server and databases list is reported  ok so some sort of comms with ML Server still do happen in 2017.3 but something is broken.

Exception message below : 

Invalid MarkLogic version: 9.0-2
uk.co.reecedunn.intellij.plugin.marklogic.server.MarkLogicVersionFormatException: Invalid MarkLogic version: 9.0-2
	at uk.co.reecedunn.intellij.plugin.marklogic.server.MarkLogicVersion$Companion.parse(MarkLogicVersion.kt:36)
	at uk.co.reecedunn.intellij.plugin.marklogic.server.MarkLogicServer.getVersion(MarkLogicServer.kt:95)
	at uk.co.reecedunn.intellij.plugin.marklogic.ui.log.MarkLogicLogViewUI$refreshAction$1.run(MarkLogicLogViewUI.kt:113)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rhdunn** [comment]
Hello,

1. I have fixed the issue running queries in IntelliJ 2017.3 in https://github.com/rhdunn/marklogic-intellij-plugin/commit/065ccb469e4a75052fc67ca9952df55bdbef0e4a, as part of the 0.3-dev work.

2. What issue are you having with sjs modules?

3. When installing from the IntelliJ plugin repository, it only seems to be using v0.1 of my plugin for 2017.2, whereas it is using v0.2 on 2017.3. I am not sure why that is, as I have published builds for the different versions. You can download the zip for the target IntelliJ version and install it manually, or build it locally from source.

4. Thank you for reporting the issue regarding MarkLogic versions. I was only supporting 2 or 4 number forms (e.g. "9.0", or "9.0-1.3"). I have pushed a fix for this to also allow 3 number forms like the one you have in the exception.

**Comment by sebvige** [comment]
Thanks Reece - all fixed
